config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  # get 'likes/create'
  # delete 'likes/destroy'

  get 'replies/create'

  devise_for :users

  resources :passwords, only:[:new, :create, :edit, :update]

  root "posts#index"
  get "view", to: 'posts#view'

  resources :posts do 
    resources :comments
  end

  post '/post/:id/like', to: 'posts#like', as: 'like' 
  get 'posts/:id/duplicate', to: 'posts#duplicate', as: 'duplicate'
  
  resources :nested_forms, only: [], param: :index do
    member do 
      delete '(:id)' => "nested_forms#destroy", as: ""
      post '/' => "nested_forms#create"
    end
  end  

  namespace :api do
    namespace :v1 do
      resources :posts, only: [:index, :show, :create,:update, :destroy]
    end
  end
  authenticate :user do
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
 # after_create_commit { broadcast_prepend_to [post, 'comments'], target: "comments_#{post.id}"}
 belongs_to :parent, class_name: 'Comment', optional: true
 has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  def archived?
    status == 'archived'
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/nested_form.rb
class NestedForm < ApplicationRecord
  belongs_to :post
 
  validates :input, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    extend FriendlyId
	  friendly_id :title, use: :slugged
  acts_as_paranoid

	has_many :comments, dependent: :destroy
	has_one_attached :image
	belongs_to :category
	belongs_to :user
	has_many :nested_forms, dependent: :destroy
	has_many :likes, dependent: :destroy
  accepts_nested_attributes_for :nested_forms, allow_destroy: true, 
                                 reject_if: :all_blank
  amoeba do
     include_association [:nested_forms]
      prepend :title => "Copy of "
 		customize(lambda { |original_object,new_object|
       	new_object.image.attach(original_object.image.blob) 	if original_object.image.attached?
 		})
  end

	validates :image, presence: true
	validates :title, presence: true, length:{ maximum: 256}, uniqueness: true
	validates :body,  presence: true, length:{ minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :recoverable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable, :lockable, :confirmable

  has_many :posts, dependent: :destroy
  has_many :comments , dependent: :destroy
  has_many :likes , dependent: :destroy

  def generate_token
    SecureRandom.hex(10)
  end
  def send_password_reset_instructions
      UserMailer.reset_password_email(self).deliver_now
  end
  
  def token_valid?
    self.reset_password_sent_at > 24.hours.ago
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.new(comment_params)

      @comment.user_id=current_user.id

    if @comment.save
      respond_to do |format|
        format.html {redirect_to @post}
        format.js
      end
    end
  end
  

  def new
    @post=Post.friendly.find(params[:post_id])
    @comment = @post.comments.new
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status, :parent_id, :like)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
  end
 end

app/controllers/nested_forms_controller.rb
class NestedFormsController < ApplicationController
  
  before_action :setup_project

  def destroy
  end
   def new
  end

  def setup_project
    @post=Post.new(nested_forms: [NestedForm.new])
  end

end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  def new
  end

  def create
    @user=User.find_by(email: params[:passwords][:email])
    if @user
      
      @user.reset_password_token = @user.generate_token
      @user.reset_password_sent_at = Time.zone.now
      @user.save
      @user.send_password_reset_instructions
      flash[:info] = 'Email is sent with password reset instructions'

      redirect_to new_user_session_path
    # else
    #   redirect_to new_user_session_path
    end

  end

  def edit
     @user=User.find(params[:id])
  end

  def update
    @user=User.find_by(email: params[:user][:email])
    debugger
    if user_valid?(params["user"]["reset_password_token"]) && @user.token_valid?
      @user.reset_password_token = nil
      @user.reset_password_sent_at = nil
      @user.encrypted_password = params[:user][:password]
      @user.save
      redirect_to new_user_session_path
    else 
      
    end

  end

  private
  def user_valid?(reset_password_token)
    reset_password_token == @user.reset_password_token
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :authenticate_user!
 before_action :get_post, only: [:show, :edit, :update, :destroy, :like, :duplicate]
	def index
		@posts=Post.all
	end

	def show
	end

	def new 
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user= current_user
		if @post.save 
			# UserMailer.welcome_email(current_user.email).deliver_now
		ExampleWorker.perform_at(1.minute.from_now, current_user.email)
			redirect_to @post
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit		
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@post.destroy

		redirect_to root_path, status: :see_other
	end

	def view
		@posts=Post.paginate(page: params[:page], per_page: 6)
	end

	def like
		Like.create(user_id: current_user.id, post_id: @post.id)
		redirect_to post_path(@post)
	end

	def duplicate
		@duplicate_post=@post.amoeba_dup
		if @duplicate_post.save
			redirect_to edit_post_path(@duplicate_post)
		else
			flash[:notice] = 'can\'t duplicate'
			redirect_to @duplicate_post
		end
	end

	private

	def post_params
		params.require(:post).permit(:title, :body, :status, :image, :category_id, :first_tag, nested_forms_attributes: [:id, :input, :_destroy])
	end

	def get_post
		@post=Post.friendly.find(params[:id])
	end
	
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def is_active?(link_path)
	  if current_page?(link_path)
	    "active"
	  else
	    ""
	  end
	end


  def isAdmin?(user)
    if user.role=='Admin'
      return true
    else
      return false
    end 
  end

  def liked?(post, user)
  	post.likes.find_by("user_id":user.id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
# def comment_count
# 	counter = 0
# 	counter+=@post.comments.count
# 	return counter
# end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/nested_forms_helper.rb
module NestedFormsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/comments/_comment.html.erb
<% unless comment.parent_id || !comment.persisted? %> 
  @<%= comment.user.name %>
 <p class="commen_t"> 
    <%= comment.body %>
 </p>
  <p class="creation-time">
    <%=comment.created_at.try(:strftime, "%d %b %Y ")%>
  </p>
  
    <% if comment.replies.any? %>
    <div class="card ml-5">
  <div class="card-body">
    <% comment.replies.each do |reply| %> 
      <%= render partial: 'comments/reply', locals: { reply: reply } %>
    <% end %>
        </div>
</div>
  <% end %>

    <%= link_to 'reply',new_post_comment_path(@post, parent_id: comment.id) %>

<br>
<br>
  
 <div id="reply_form_<%= comment.id %>"></div>
 <% end %>

app/views/comments/_count.html.erb
<!-- <%#= turbo_frame_tag "comment_count" do %>
 <p>
  Total no. of comments: <%#= counter = @post.comments.count %>
 </p>
<%#end %> -->

app/views/comments/_form.html.erb
  <%= form_with model:[ @post, @post.comments.build ], local: false do |form| %>
    <p>
      <%= form.text_field :body, class:"comment-text form-control",placeholder:"Add comment" %>
    </p>
    <p>
      <%= form.submit 'Submit',class:"comment-button" %>
    </p>
  <% end %>

app/views/comments/_reply.html.erb
@<%= reply.user.name %><br>
<%=reply.body%>
<br>
<%= link_to 'reply',new_post_comment_path(@post, parent_id: reply.id) %>
<br>
<% if reply.replies.any? %>
<div class="card ml-5">
  <div class="card-body">
	<% reply.replies.each do |reply2| %> 
  @<%= reply2.user.name %><br>
	<%= reply2.body %> 
	<br>
	<% end %>
	</div>
</div>
<% end %>

app/views/comments/_reply_form.html.erb
<%= form_with(model: [@post, @post.comments.build]) do |form|%>

	<%= form.hidden_field :parent_id, value: params[:parent_id] %>
	<%= form.label "reply" %>
	<%= form.text_field :body %>

	<%= form.submit 'submit' %>
<% end %>

app/views/comments/create.js.erb
// $("#show_comments").html("<%= escape_javascript render(partial: 'comments/comment', locals: { comment: @comment }) %>");

app/views/comments/new.html.erb
<%= form_with(model: [@post, @post.comments.build]) do |form|%>

	<%= form.hidden_field :parent_id, value: params[:parent_id] %>
	<%= form.label "reply" %>
	<%= form.text_field :body %>

	<%= form.submit 'submit' %>
<% end %>

app/views/comments/new.js.erb
document.querySelector("reply_form_<%= comment.id %>)".innerHTML= ("<%= j render 'reply_form', comment: @comment %>")