config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  # get 'likes/create'
  # delete 'likes/destroy'

  get 'replies/create'

  devise_for :users

  resources :passwords, only:[:new, :create, :edit, :update]

  root "posts#index"
  get "view", to: 'posts#view'

  resources :posts do 
    resources :comments
  end

  post '/post/:id/like', to: 'posts#like', as: 'like' 
  get 'posts/:id/duplicate', to: 'posts#duplicate', as: 'duplicate'
  
  resources :nested_forms, only: [], param: :index do
    member do 
      delete '(:id)' => "nested_forms#destroy", as: ""
      post '/' => "nested_forms#create"
    end
  end  

  namespace :api do
    namespace :v1 do
      resources :posts, only: [:index, :show, :create,:update, :destroy]
    end
  end
  authenticate :user do
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/models/post.rb
class Post < ApplicationRecord
    extend FriendlyId
	  friendly_id :title, use: :slugged
  acts_as_paranoid

	has_many :comments, dependent: :destroy
	has_one_attached :image
	belongs_to :category
	belongs_to :user
	has_many :nested_forms, dependent: :destroy
	has_many :likes, dependent: :destroy
  accepts_nested_attributes_for :nested_forms, allow_destroy: true, 
                                 reject_if: :all_blank
  amoeba do
     include_association [:nested_forms]
      prepend :title => "Copy of "
 		customize(lambda { |original_object,new_object|
       	new_object.image.attach(original_object.image.blob) 	if original_object.image.attached?
 		})
  end

	validates :image, presence: true
	validates :title, presence: true, length:{ maximum: 256}, uniqueness: true
	validates :body,  presence: true, length:{ minimum: 10 }
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApiController

   skip_before_action :verify_authenticity_token
       

  def index
    @posts=Post.all
    render json: @posts
  end

  def show
    @post=Post.find_by(id: params[:id])
      if @post
        render json: @post, status: 200 
      else 
        render json: {
          error: "post not found..."
        }
      end
  end

  def create
   @post=Post.new(post_params)

    if @post.save
      render json: @post
    else
      render json:{
      error: "Error creating..."
      }
    end 
  end

  def update
    @post=Post.find(params[:id])

    if @post.update(post_params)
      render json: @post
    else
      render json:{
        error: "post not found..."
      }
    end
  end

  def destroy
     @post=Post.find(params[:id])
     
     if @post
        @post.destroy
        render json: "Article is deleted!"
     end
  end

  def post_params
    params.require(:post).permit(:title, :body, :status, :image, :category_id)
  end

    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :authenticate_user!
 before_action :get_post, only: [:show, :edit, :update, :destroy, :like, :duplicate]
	def index
		@posts=Post.all
	end

	def show
	end

	def new 
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user= current_user
		if @post.save 
			# UserMailer.welcome_email(current_user.email).deliver_now
		ExampleWorker.perform_at(1.minute.from_now, current_user.email)
			redirect_to @post
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit		
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@post.destroy

		redirect_to root_path, status: :see_other
	end

	def view
		@posts=Post.paginate(page: params[:page], per_page: 6)
	end

	def like
		Like.create(user_id: current_user.id, post_id: @post.id)
		redirect_to post_path(@post)
	end

	def duplicate
		@duplicate_post=@post.amoeba_dup
		if @duplicate_post.save
			redirect_to edit_post_path(@duplicate_post)
		else
			flash[:notice] = 'can\'t duplicate'
			redirect_to @duplicate_post
		end
	end

	private

	def post_params
		params.require(:post).permit(:title, :body, :status, :image, :category_id, :first_tag, nested_forms_attributes: [:id, :input, :_destroy])
	end

	def get_post
		@post=Post.friendly.find(params[:id])
	end
	
end

app/views/posts/_form1.html.erb
<%= form_with model: post , name: 'my_form', id: "form1" do |form| %>
  
  
  <div>
    <%= form.label :title, class:"form-label"%><br>
    <%= form.text_field :title, class:"form-text",placeholder:"Give title to your Blog " %>
      <div class="title-error"></div>

    <% post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div >
    <%= form.label :body, class:"form-label"%><br>
    <%= form.text_area :body, class:"form-text-body",placeholder:"Write your Blog..."%><br>
      <div class="body-error"></div>

    <% post.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="new-bottom">

   <br>

   <div class="image-category">

    <%= form.file_field :image, class:"image-field "%>

    <% post.errors.full_messages_for(:image).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

    <div class="image-error"></div>
    <br>
    <%= form.select :category_id, options_for_select(Category.all.map { |category| [category.name, category.id] }), {prompt: "Select category"}, class:"form-control category-dropdown " %>
    <br>
    <br>
    <%= form.submit "Add tag", 
          formaction: nested_form_path(@post.nested_forms.size), 
          formmethod: :post, 
          formnovalidate: true, 
          id: "add-tag"%>
    <div id="nested_forms">
      <%= form.fields_for :nested_forms do |task_form| %>
        <%= render "nested_forms/form", form: task_form %>
      <% end %>
    </div>

     <div>
         <%= form.submit 'Submit', class:"submit-button"%>
    </div>

  </div>

<% end %>

app/views/posts/edit.html.erb
<div class="edit-page-top">
<h1 class="show-head">Keep Hustling...</h1>
<h1 class="new-head2">Edit your blog</h1>
</div>
<br>
<section id="scroll">
  <div class="container">
        <div class="col-lg-6 order-lg-1">
            <div class="p-5">
               <%= render partial: "form1", locals: { post: @post } %>
            </div>
        </div>
  </div>
</section>

app/views/posts/index.html.erb
<div class="py-5 bg-light border-bottom mb-4" style="background-image: url('<%=asset_path('home-bg.jpg')%>')">
<br>
<br>
<br>
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder">Welcome to Blog Home!</h1>
            <p class="lead mb-0">Here you can read blogs and create your own blog</p>
        </div>
    </div>
    <div class="center-div">
    <%= link_to "View all blogs", view_path, class:"btn button-link index-button" %>
    <% if isAdmin?(current_user) %>
     <%= link_to "Create your blog", new_post_path, class:"btn button-link index-button"%>
     <% end %>
</div>
</div>

app/views/posts/new.html.erb
<div class="new-page-top">
<h1 class="new-head">Post your passion, your way</h1>
<h3 class="new-head2"> Create a unique and beautiful Blog </h3>
</div>
<br>

<section id="scroll">
	<div class="container">
        <div class="col-lg-6 order-lg-1">
            <div class="p-5">
               <%= render partial: "form1", locals: { post: @post } %>
            </div>
        </div>
	</div>
</section>
               <%#= render partial: "form" %>

<br>
<br>

app/views/posts/show.html.erb
<div style="background-color: white;">
    <article class="show-article">
    	<br>
    	<header class="mb-4 " >
    	<h1 class="fw-bolder mb-1 show-head"><%= @post.title %></h1>
    	</header>	
    	<figure class="mb-4">
             <% if @post.image.attached? %>
    		  <%= image_tag url_for(@post.image), class:"img-fluid rounded" %>
             <%end%>
    	</figure>
    <br>
    	<section class="mb-5">   	    
    	    <p class="fs-5 mb-4"><%= @post.body %></p>
    	</section>
        <div>
        <% @post.nested_forms.each do |tag| %>
            <span class="post-tags">
                <%= tag.input %>
            </span>    
        <% end %> 
        </div>       
    </article>

    <% if isAdmin?(current_user) %>
    <br>
    <ul class="show-div">
    		<%= link_to "Edit", edit_post_path(@post), class:"btn show-link show-button-edit" %>
    	 	<%= link_to "Delete", post_path(@post) ,data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                      }, class:"btn show-link show-button-delete"%>
    </ul>

    <% else %>

    <% if liked?(@post, current_user) %>
        <%= button_to like_path(@post), disabled:true do%>
        <i class="fa-solid fa-heart fa-2xl" style="color: #d93012;"></i>
        <% end %>
    <% else %>
        <%= button_to like_path(@post) do%>
        <i class="fa-regular fa-heart fa-2xl" style="color: #000205;"></i>
        <% end %>
    <% end %>
        <i class="fa-regular fa-thumbs-up fa-lg" style="color: #070808;"></i> <%=@post.likes.count%>
    <h4 class="comment-head"><strong>Comment</strong></h4>
    <hr class="show-ruler">
    <div class="comment-form">
        <%= render 'comments/form', locals: { comment: Comment.new }%>
    </div>
    <div class="comment-section">
        <%= render 'comments/count'%>
    </div>
    <% end %>
    <div class="comment-section">
        <div id="show_comments">
           <% @post.comments.each do |comment| %>
            <%= render comment %>
            <% end %>
        </div>
    </div>
    <hr class="show-ruler">   
    <br>
    <footer class="border-top">
    	   <br>
                <div class="container px-4 px-lg-5">
                    <div class="row gx-4 gx-lg-5 justify-content-center">
                        <div class="col-md-10 col-lg-8 col-xl-7">
                            <ul class="list-inline text-center">
                                <li class="list-inline-item">
                                    <a href="#!">
                                        <span class="fa-stack fa-lg">
                                            <i class="fas fa-circle fa-stack-2x"></i>
                                            <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                        </span>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#!">
                                        <span class="fa-stack fa-lg">
                                            <i class="fas fa-circle fa-stack-2x"></i>
                                            <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                        </span>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#!">
                                        <span class="fa-stack fa-lg">
                                            <i class="fas fa-circle fa-stack-2x"></i>
                                            <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                        </span>
                                    </a>
                                </li>
                            </ul>
                            <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                        </div>
                    </div>
                </div>
    </footer>
</div>

app/views/posts/view.html.erb
<div style="background-image: url('<%=asset_path('home-bg.jpg')%>')">
<h1 class="view-head"><b>Hey</b>, see our thoughts, stories and ideas...</h1>
	<div class="card-boxes">
		<% @posts.each do |post| %>
			  <div class="card">
				  <% if post.image.attached? %>
				  <%= image_tag url_for(post.image),class:"card-img-top img-card"  %>
				  <% end %>
				<div class="card-body">
			      <h5 class="card-title">
			      	<%= link_to post.title , post_path(post),class:"card-link"%>
      		  </h5>			
			   	</div>
			    <div class="card-footer">
			      <small class="text-muted">
			      	<p class="creation-time">
            		<%=post.created_at.try(:strftime, "%d %b %Y  %H:%M %p")%>

				  		  <%= link_to duplicate_path(post) do %>
				  		  <i class="fa-regular fa-copy fa-xl" style="color: #010409;float: right;"></i>
				  		  <% end %>
							</p>	
	      	  </small>
			    </div>
			  </div>
		<% end %>
	</div>
		<%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>